<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Funny</title>
	<link rel="stylesheet"  href="css/jquery.mobile-1.3.2.min.css">
	<link rel="stylesheet" href="css/main.css">
	<link rel="shortcut icon" href="favicon.ico">
	<!-- <script type="text/javascript" charset="utf-8" src="cordova.js"></script>  -->	
	<script src="js/jquery.js"></script>
	<script src="js/index.js"></script>
	<script src="js/jquery.mobile-1.3.2.min.js"></script>	
	
</head>
<body>